name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Download and Push Image" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 确保 .bing 目录存在
      - name: Ensure .bing directory exists
        run: mkdir -p .bing && ls -al .bing

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .bing  # 需要部署的目录
          branch: gh-pages  # 确保推送到 gh-pages 分支
