name: Deploy to GitHub Pages

on:
  # 当代码推送到 main 分支时触发工作流
  push:
    branches:
      - main
  # 允许手动触发工作流
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: 第一步：检出代码
        uses: actions/checkout@v4

      # 第二步：设置 BING_DIR 环境变量
      - name: 第二步：设置 BING_DIR 环境变量
        run: echo "BING_DIR=./bing" >> $GITHUB_ENV

      # 第三步：安装必要的依赖（如果 Markdown 需要转换为 HTML 等）
      - name: 第三步：安装必要的依赖
        run: |
          # 如果需要将 Markdown 转换为 HTML，可以安装 pandoc
          sudo apt-get update
          sudo apt-get install -y pandoc

      # 第四步：处理 Markdown 文件（如果需要）
      - name: 处理 Markdown 文件
        run: |
          # 示例：将 Markdown 文件转换为 HTML
          if [ -d "$BING_DIR" ]; then
            for md_file in $BING_DIR/*.md; do
              if [ -f "$md_file" ]; then
                html_file="${md_file%.*}.html"
                pandoc "$md_file" -o "$html_file"
              fi
            done
          fi
      # 第五步：清空目标分支的文件
      - name: 清空gh-pages 分支的文件
        uses: actions/checkout@v4
        with:
          ref: gh-pages  # 假设 GitHub Pages 使用的是 gh-pages 分支
          path: gh-pages
      - name: 删除目标分支的所有文件
        run: |
          cd gh-pages
          rm -rf *
          cd ..
      - name: 检查 bing 目录是否存在
        run: |
          if [ ! -d "${{ env.BING_DIR }}" ]; then
            echo "bing 目录不存在，终止工作流。"
            exit 1
          fi
      # 第六步：部署到 GitHub Pages
      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.BING_DIR }}
