name: Convert Markdown to HTML and Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main  # 监听 main 分支的变化

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Convert Markdown to HTML
      run: |
        mkdir -p output
        for file in $(find ./content -name '*.md'); do
          filename=$(basename "$file" .md)
          pandoc "$file" -o "output/$filename.html" --standalone --css=style.css
        done

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v2
      with:
        api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        project-name: 'your-cloudflare-pages-project'  # 替换为你的 Cloudflare Pages 项目名称
        directory: './output'  # 生成的 HTML 文件所在目录
